version: '3'
volumes:
  elasticsearch-data:
    driver: local
services:
  elasticsearch:
    restart: always
    image: elasticsearch:6.4.3
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data/
    ports:
      - 59200:9200
      - 59300:9300
    environment:
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
      discovery.type: single-node

